version: '3'

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zael-wad/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o : bind
      device: /home/zael-wad/data/wordpress

networks:
  inception:
    driver: bridge


services:
  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:42
    container_name: mariadb
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 1000000
    volumes:
     - data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

    
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:43
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      mariadb:
        condition: service_healthy

    env_file:
      - .env
    restart: always


  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx:42
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always



